%YAML:1.0
version: "0.0"
FeatureDetector: GridSIFT
DescriptorExtractor: SIFT
camera_intrinsic_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 518., 0., 3.2550000000000000e+02, 0., 519.,
       2.5350000000000000e+02, 0., 0., 1. ]
scaling_factor: 1000
good_match_threshold: 4
start_index: "1"
end_index: "700"
voxel_grid: "0.01"
min_good_match: "10"
min_inliers: "5"
max_norm: "0.3"
min_tolerance: "0.1"